clever_transform:
  outputs:
    dev:
      dbname: clever
      host: localhost
      pass: clever
      port: 5433
      schema: raw
      threads: 8
      type: postgres
      user: clever
    prod:
      dbname: clever
      host: postgres_clever
      pass: clever
      port: 5432
      schema: raw
      threads: 8
      type: postgres
      user: clever
  target: dev
