SELECT
    canadian_driver_inspections::NUMERIC,
    canadian_driver_out_of_service::NUMERIC,
    canadian_driver_out_of_service_pct::NUMERIC,
    canadian_vehicle_inspections::NUMERIC,
    canadian_vehicle_out_of_service::NUMERIC,
    canadian_vehicle_out_of_service_pct::NUMERIC,
    cargo_types::TEXT,
    carrier_safety_rating_rating::TEXT AS carrier_safety_rating,
    carrier_safety_rating_rating_date::DATE AS carrier_safety_rating_date,
    carrier_safety_rating_review_date::TEXT,
    carrier_safety_rating_type::TEXT,
    carrier_type::TEXT,
    date_created::TIMESTAMP AS created_at,
    date_updated::TIMESTAMP AS updated_at,
    dba_name::TEXT,
    drivers::NUMERIC AS drivers_count,
    duns_number::TEXT,
    entity_type::TEXT,
    fmcsa_link::TEXT,
    legal_name::TEXT,
    mailing_address::TEXT,
    mc_num::TEXT,
    mcs_150_form_date::DATE,
    mileage::NUMERIC,
    mileage_year::NUMERIC,
    oos_date::DATE,
    operating_status::TEXT,
    operation_classification::TEXT,
    phone::TEXT,
    physical_address::TEXT,
    power_units::NUMERIC AS power_units_count,
    -- state_carrier_id_number::NUMERIC  -- ALL NULL
    us_crashes_fatal::NUMERIC AS us_crashes_fatal_count,
    us_crashes_injury::NUMERIC AS us_crashes_injury_count,
    us_crashes_total::NUMERIC AS us_crashes_total_count,
    us_crashes_tow::NUMERIC AS us_crashes_tow_count,
    us_driver_inspections::NUMERIC AS us_driver_inspections_count,
    us_driver_natl_avg_oos_pct::NUMERIC AS us_driver_natl_avg_oos_pct,
    us_driver_out_of_service::NUMERIC AS us_driver_out_of_service_count,
    us_driver_out_of_service_pct::NUMERIC AS us_driver_out_of_service_pct,
    us_hazmat_inspections::NUMERIC AS us_hazmat_inspections_count,
    us_hazmat_natl_avg_oos_pct::NUMERIC AS us_hazmat_natl_avg_oos_pct,
    us_hazmat_out_of_service::NUMERIC AS us_hazmat_out_of_service_count,
    us_hazmat_out_of_service_pct::NUMERIC AS us_hazmat_out_of_service_pct,
    us_iep_inspections::NUMERIC AS us_iep_inspections_count,
    us_iep_natl_avg_oos_pct::NUMERIC AS us_iep_natl_avg_oos_pct,
    us_iep_out_of_service::NUMERIC AS us_iep_out_of_service_count,
    us_iep_out_of_service_pct::NUMERIC AS us_iep_out_of_service_pct,
    us_vehicle_inspections::NUMERIC AS us_vehicle_inspections_count,
    us_vehicle_natl_avg_oos_pct::NUMERIC AS us_vehicle_natl_avg_oos_pct,
    us_vehicle_out_of_service::NUMERIC AS us_vehicle_out_of_service_count,
    us_vehicle_out_of_service_pct::NUMERIC AS us_vehicle_out_of_service_pct,
    usdot_num::NUMERIC AS company_id,
    user_created::TEXT AS created_by,
    user_updated::TEXT AS updated_by
FROM {{ source('clever_raw', 'fmcsa_safer_data') }}