{{ config(
    alias='company_profiles_google_maps',
    materialized='table',
    indexes=[
        {'columns': ['place_id'], 'type': 'btree'}
    ]
) }}

SELECT
    area_service,
    booking_appointment_link,
    borough,
    business_status,
    category,
    cid,
    city,
    country,
    country_code,
    description,
    full_address,
    google_id,
    latitude,
    located_google_id,
    located_in,
    location_link,
    logo,
    longitude,
    menu_link,
    name,
    order_links,
    owner_id,
    owner_link,
    owner_title,
    phone,
    photo_url,
    photos_count,
    place_id,
    plus_code,
    popular_times,
    postal_code,
    range,
    rating,
    reservation_links,
    reviews,
    reviews_id,
    reviews_link,
    reviews_tags,
    site,
    state,
    street,
    street_view,
    subtypes,
    time_zone,
    type,
    typical_time_spent,
    us_state,
    verified
FROM {{ ref('company_profiles_google_maps_typed') }}